---
name: Mac test

on:
  workflow_dispatch:
  push:
    branches: ["*"]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  create-local-k8s:
    runs-on: macos-13
    env:
      ACTIONS_STEP_DEBUG: true
      ACTIONS_RUNNER_DEBUG: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and Install OrbStack via Brew
        run: |
          # We are using OrbStack 1.5.1 since the CPU for GitHub shared runners is not supported by later versions.
          # ARM based runners do not support nested virtualization so we can't install OrbStack on them either.
          curl -sLo orbstack.rb https://raw.githubusercontent.com/Homebrew/homebrew-cask/65da904d37b45eb3f0644e6419ebde37ef927f20/Casks/o/orbstack.rb
          brew install --cask ./orbstack.rb
          if command -v orb 2>/dev/null ; then
            docker context use orbstack
            echo "Starting orbstack" && (nohup orb start &)
            orb start

      - name: Install asdf for macOS
        run: |
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.1
          echo '. $HOME/.asdf/asdf.sh' >> ~/.zshrc
          source ~/.zshrc
          asdf plugin add caf-scripts https://github.com/AdaptiveConsulting/asdf-caf-scripts.git
          echo .tool-versions
          cut -d' ' -f1 .tool-versions | xargs -I{} asdf plugin-add {} || true
          asdf install
          orb status
          while ! docker ps >/dev/null 2>&1 ; do
            sleep 10
            echo "Waiting: $(date)"
          done
          caf_create_local_k8s.sh
          # caf_route_to_local_k8s.sh

      # - name: Test local meta charts
      #   run: |
      #     direnv exec . which caf_create_local_k8s.sh
