---
name: Mac test

on:
  workflow_dispatch:
  push:
    branches: ["*"]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  create-local-k8s:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and Install OrbStack DMG file
        run: |
          curl -L -o OrbStack.dmg https://cdn-updates.orbstack.dev/amd64/OrbStack_v1.5.1_16857_amd64.dmg
          app_location=$(hdiutil attach OrbStack.dmg | tail -n 1 | tr -s "[:blank:]" "\n")
          echo $app_location
          find $app_location -name "*.app" -exec cp -R {} /Applications \;
          hdiutil detach $app_location

      # - name: Install asdf for macOS
      #   run: |
      #     git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.1
      #     echo '. $HOME/.asdf/asdf.sh' >> ~/.zshrc
      #     source ~/.zshrc
      #     asdf plugin add caf-scripts https://github.com/AdaptiveConsulting/asdf-caf-scripts.git
      #     echo .tool-versions
      #     cut -d' ' -f1 .tool-versions | xargs -I{} asdf plugin-add {} || true
      #     caf_create_local_k8s.sh


      # - name: Create Local K8s
      #   run: |
      #     caf_create_local_k8s.sh

      # - name: Route to Local K8s
      #   run: |
      #     caf_route_to_local_k8s.sh

      # - name: Test local meta charts
      #   run: |
      #     direnv exec . which caf_create_local_k8s.sh
