---
name: Mac test

on:
  workflow_dispatch:
  # push:
  #   branches: ["*"]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  pre-clean:
    if: ${{ ! github.event.pull_request.draft }}
    runs-on: caf-adaptive-mac
    steps:
      - name: Reset OrbStack
        run: |
          echo "Resetting OrbStack and deleting all data..."
          if orb reset -y; then
            echo "Done"
          else
            echo "Failed to reset OrbStack."
            exit 1
          fi

  create-local-k8s:
    runs-on: caf-adaptive-mac
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install asdf for macOS
        run: |
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.1
          echo '. $HOME/.asdf/asdf.sh' >> ~/.zshrc
          source ~/.zshrc
          asdf plugin add caf-scripts "https://github.com/AdaptiveConsulting/asdf-caf-scripts.git?ref=CAF-439-asdf-caf-script-tests"
          echo .tool-versions
          cut -d' ' -f1 .tool-versions | xargs -I{} asdf plugin-add {} || true
          asdf install
          caf_create_local_k8s.sh
          # caf_route_to_local_k8s.sh

      # - name: Test local meta charts
      #   run: |
      #     direnv exec . which caf_create_local_k8s.sh
