---
name: Mac test

on:
  workflow_dispatch:
  push:
    branches: ["*"]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  create-local-k8s:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install asdf for macOS
        run: |
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.1
          echo '. $HOME/.asdf/asdf.sh' >> ~/.zshrc
          source ~/.zshrc
          asdf plugin add caf-scripts https://github.com/AdaptiveConsulting/asdf-caf-scripts.git
          asdf install caf-scripts 1.5.0
          asdf list-all caf-scripts
          which caf_create_local_k8s.sh
          which caf_route_to_local_k8s.sh
          caf_create_local_k8s.sh

      # - name: Create Local K8s
      #   run: |
      #     caf_create_local_k8s.sh

      # - name: Route to Local K8s
      #   run: |
      #     caf_route_to_local_k8s.sh

      # - name: Test local meta charts
      #   run: |
      #     direnv exec . which caf_create_local_k8s.sh
