---
name: Linux test

on:
  workflow_dispatch:
  push:
    branches: ["*"]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  create-local-k8s:
    runs-on: ubuntu-latest
    env:
      MINIKUBE_VERSION: "latest"
      ASDF_VERSION: "v0.14.1"
      CAF_SCRIPTS_REPO: "https://github.com/AdaptiveConsulting/asdf-caf-scripts.git?ref=main"
      CAF_LCL_K8S_MEMORY: "8" #GB
      ASDF_DIR: /opt/asdf

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          # Install Minikube
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/${{ env.MINIKUBE_VERSION }}/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/
          which minikube
          git clone https://github.com/asdf-vm/asdf.git ${{ env.ASDF_DIR }} --branch ${{ env.ASDF_VERSION }}
          . "${{ env.ASDF_DIR }}/asdf.sh"
          asdf plugin-add caf-scripts .
          cut -d' ' -f1 .tool-versions | xargs -I{} asdf plugin-add {} || true
          asdf install && echo "ASDF INSTALL"
          echo "ASDF INSTALL DONE" 
          echo "$(asdf plugin list)"
          # ./scripts/caf_route_to_local_k8s.sh

      - name: Run scripts
        run: |
          ./scripts/caf_create_local_k8s.sh

